<?php

//
// Copyright (C) 2013 - 2018 FromDual GmbH
//
// This software is licensed under GPL v2: http://www.gnu.org/licenses/gpl-2.0.html
//

define('OK', 0);

// LogLevel Old

define('ERR',  1);
define('WARN', 2);
define('INFO', 3);
define('DBG',  4);

// LogLevel New
// https://en.wikipedia.org/wiki/Syslog
// define('EMERGENCY', 0);  // Do NOT use this one!
/*
define('ALERT',     1);
define('CRITICAL',  2);
define('ERROR',     3);
define('WARNING',   4);
define('NOTICE',    5);
define('INFO',      6);
define('DEBUG',     7);
*/

?>
